sudo: false
dist: xenial
language: node_js
node_js: 8.11
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  chrome: stable
install: npm install
before_script: 'gulp lint version:check'
script: echo "Disabled tests until we reach a beta candidate for the themes."

